# Nom de l'application
spring.application.name=jobs

# =========================
# Configuration PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/jobs42
spring.datasource.username=postgres
spring.datasource.password=Discovery@123456
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# Hibernate / JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true                     
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Serveur
# =========================
server.port=9090

# =========================
# JWT Configuration
# =========================
jwt.client_id=u-s4t2af-23f031abd5ab1c7afcd6b43148ddd70b2ae20692602fb8c142f94fabb55b5373
jwt.client_secret=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
jwt.redirect_uri=http://localhost:9090/auth/callback