# Nom de l'application
spring.application.name=jobs

# =========================
# Configuration PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/jobs42
spring.datasource.username=postgres
spring.datasource.password=Discovery@123456
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# Hibernate / JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true                     
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Serveur
# =========================
server.port=9090
